[package]
name = "test_openblas_system"
version = "0.1.0"
edition = "2021"

[dependencies]
# xprec-svd依存
xprec-svd = { path = "../xprec-svd" }

# ndarray依存
ndarray = "0.15"

# システムOpenBLASを使用（static）
ndarray-linalg = { version = "0.16", features = ["openblas-static"] }