[package]
name = "sparseir-rust"
version = "0.1.0"
edition = "2021"
description = "Rust implementation of SparseIR functionality"
license = "MIT"
repository = "https://github.com/sparseir-rust/sparseir-rust"

[dependencies]
# Core linear algebra
ndarray = "0.15"
nalgebra = "0.32"
# ndarray-linalg removed - using xprec-svd for SVD instead

# Extended precision
twofloat = "0.2"
num-traits = "0.2"
num-complex = "0.4"

# Special functions
special = "0.2"
statrs = "0.16"

# Error handling
thiserror = "1.0"

# High-precision SVD (internal dependency)
xprec-svd = { path = "../xprec-svd" }

# Parallel processing
rayon = "1.7"

[dev-dependencies]
approx = "0.5"
proptest = "1.0"

